Convert pipeline conditions to template expressions

diff --git a/eng/pipelines/templates/steps/vmr-pull-updates.yml b/eng/pipelines/templates/steps/vmr-pull-updates.yml
--- a/eng/pipelines/templates/steps/vmr-pull-updates.yml
+++ b/eng/pipelines/templates/steps/vmr-pull-updates.yml
@@ -36,15 +36,14 @@ steps:
   displayName: Prepare branch ${{ parameters.vmrBranch }}
   workingDirectory: ${{ parameters.vmrPath }}
 
-- script: |
-    mkdir -p ${{ parameters.vmrPath }}/artifacts/x64/Release
-  displayName: Create artifacts folder (Unix)
-  condition: ne(variables['Agent.OS'], 'Windows_NT')
-
-- powershell: |
-    New-Item -ItemType Directory -Path ${{ parameters.vmrPath }}/artifacts/x64/Release
-  displayName: Create artifacts folder (Windows)
-  condition: eq(variables['Agent.OS'], 'Windows_NT')
+- ${{ if eq(variables['Agent.OS'], 'Windows_NT') }}:
+  - powershell: |
+      New-Item -ItemType Directory -Path ${{ parameters.vmrPath }}/artifacts/x64/Release
+    displayName: Create artifacts folder
+- ${{ else }}:
+  - script: |
+      mkdir -p ${{ parameters.vmrPath }}/artifacts/x64/Release
+    displayName: Create artifacts folder
 
 - script: |
     git config --global user.name "dotnet-maestro[bot]"
@@ -58,45 +57,44 @@ steps:
   displayName: Prepare .artifactignore
   workingDirectory: $(Agent.TempDirectory)
 
-- script: >
-    ./eng/vmr-sync.sh
-    --vmr ${{ parameters.vmrPath }}
-    --tmp $(Agent.TempDirectory)
-    --azdev-pat '$(dn-bot-all-orgs-code-r)'
-    --branch ${{ parameters.vmrBranch }}
-    --repository "installer:${{ parameters.targetRef }}"
-    --recursive
-    --remote "installer:$(Agent.BuildDirectory)/installer"
-    --component-template $(Agent.BuildDirectory)/installer/src/VirtualMonoRepo/Component.template.md
-    --tpn-template $(Agent.BuildDirectory)/installer/src/VirtualMonoRepo/THIRD-PARTY-NOTICES.template.txt
-    --debug
-    ||
-    (echo "##vso[task.logissue type=error]Failed to synchronize the VMR" && exit 1)
-  displayName: Synchronize dotnet/dotnet (Unix)
-  condition: ne(variables['Agent.OS'], 'Windows_NT')
-  workingDirectory: $(Agent.BuildDirectory)/installer
+- ${{ if eq(variables['Agent.OS'], 'Windows_NT') }}:
+  - powershell: >
+      ./eng/vmr-sync.ps1 `
+      -vmr ${{ parameters.vmrPath }} `
+      -tmp $(Agent.TempDirectory) `
+      -azdevPat '$(dn-bot-all-orgs-code-r)' `
+      -branch ${{ parameters.vmrBranch }} `
+      -repository "installer:${{ parameters.targetRef }}" `
+      -recursive `
+      # passing remote fails for some reason, but it is the default anyway
+      # -remote "installer:$(Agent.BuildDirectory)/installer"
+      -componentTemplate $(Agent.BuildDirectory)/installer/src/VirtualMonoRepo/Component.template.md `
+      -tpnTemplate $(Agent.BuildDirectory)/installer/src/VirtualMonoRepo/THIRD-PARTY-NOTICES.template.txt `
+      -debugOutput
 
-- powershell: >
-    ./eng/vmr-sync.ps1 `
-    -vmr ${{ parameters.vmrPath }} `
-    -tmp $(Agent.TempDirectory) `
-    -azdevPat '$(dn-bot-all-orgs-code-r)' `
-    -branch ${{ parameters.vmrBranch }} `
-    -repository "installer:${{ parameters.targetRef }}" `
-    -recursive `
-    # passing remote fails for some reason, but it is the default anyway
-    # -remote "installer:$(Agent.BuildDirectory)/installer"
-    -componentTemplate $(Agent.BuildDirectory)/installer/src/VirtualMonoRepo/Component.template.md `
-    -tpnTemplate $(Agent.BuildDirectory)/installer/src/VirtualMonoRepo/THIRD-PARTY-NOTICES.template.txt `
-    -debugOutput
-
-    if ($LASTEXITCODE -ne 0) {
-      echo "##vso[task.logissue type=error]Failed to synchronize the VMR"
-      exit 1
-    }
-  displayName: Synchronize dotnet/dotnet (Windows)
-  condition: eq(variables['Agent.OS'], 'Windows_NT')
-  workingDirectory: $(Agent.BuildDirectory)/installer
+      if ($LASTEXITCODE -ne 0) {
+        echo "##vso[task.logissue type=error]Failed to synchronize the VMR"
+        exit 1
+      }
+    displayName: Synchronize dotnet/dotnet
+    workingDirectory: $(Agent.BuildDirectory)/installer
+- ${{ else }}:
+  - script: >
+      ./eng/vmr-sync.sh
+      --vmr ${{ parameters.vmrPath }}
+      --tmp $(Agent.TempDirectory)
+      --azdev-pat '$(dn-bot-all-orgs-code-r)'
+      --branch ${{ parameters.vmrBranch }}
+      --repository "installer:${{ parameters.targetRef }}"
+      --recursive
+      --remote "installer:$(Agent.BuildDirectory)/installer"
+      --component-template $(Agent.BuildDirectory)/installer/src/VirtualMonoRepo/Component.template.md
+      --tpn-template $(Agent.BuildDirectory)/installer/src/VirtualMonoRepo/THIRD-PARTY-NOTICES.template.txt
+      --debug
+      ||
+      (echo "##vso[task.logissue type=error]Failed to synchronize the VMR" && exit 1)
+    displayName: Synchronize dotnet/dotnet
+    workingDirectory: $(Agent.BuildDirectory)/installer
 
 - publish: $(Agent.TempDirectory)
   artifact: $(System.JobDisplayName)_FailedPatches
